call psc statement data api for delete delta
companieshouse/psc-statement-delta-consumer pull request #14
Opened 2023-02-03 12:48 UTC by beldhoCH

2023-02-03 13:27 UTC, JAndrewCH requested changes

2023-02-03 13:27 UTC, JAndrewCH commented on src/main/java/uk/gov/companieshouse/pscstatement/delta/service/ResponseHandler.java
> +                String msg = "server error with 404 NOT_FOUND returned from psc-statements-data-api";
Would we just get this if we are trying to delete a statement that isn't in Mongo? Not sure if it makes sense to retry in that scenario.

2023-02-03 13:46 UTC, JAndrewCH approved these changes

2023-02-06 08:51 UTC, bcullerton reviewed
Do retrys actually work for non 400 error responses? I can't see any function to intercept and serialize a kafka message in the consumer on a Retry exception

2023-02-10 11:47 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/pscstatement/delta/serialization/ChsDeltaSerializerTest.java
> +    private String payload = "{\"data\": \"{\\n  \\\"company_number\\\": \\\"09950914\\\"," +
Could we call the TestHelper to create this payload so we test against a delta? Maybe as well as a string as opposed to instead of

2023-02-10 11:47 UTC, bcullerton commented on src/main/java/uk/gov/companieshouse/pscstatement/delta/exception/RetryableErrorInterceptor.java
> +        if (LoggingConfig.getLogger() != null) {
Could we use a bean for this logger rather than a static call for it?

2023-02-10 11:47 UTC, bcullerton commented on src/main/java/uk/gov/companieshouse/pscstatement/delta/consumer/PscStatementDeltaConsumer.java
> +                                    @Header(KafkaHeaders.OFFSET) String offset) throws IOException,
Should our consumer be throwing exceptions? I'd prefer us to have caught and handled as retry/non-retryables

2023-02-10 13:29 UTC, bcullerton approved these changes

2023-02-10 13:33 UTC, merged